[package]
name = "rut-io-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blocking-server"
path = "src/blocking-server/blocking_server.rs"

[[bin]]
name = "poll-server"
path = "src/poll_server/poll_server.rs"

[[bin]]
name = "kqueue-server"
path = "src/kqueue_server/kqueue_server.rs"

[[bin]]
name = "poll-server-client"
path = "src/async-runtime/poll-async.rs"

[dependencies]
libc = "0.2.172"
nix = { version = "0.30.1" , features = ["event"]}
