[package]
name = "rut-io-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blocking-server"
path = "src/blocking-server/blocking_server.rs"

[[bin]]
name = "blocking-client_server"
path = "src/blocking-client-server/blocking_client_server.rs"

[[bin]]
name = "blocking-client"
path = "src/blocking-client/blocking_client.rs"

[[bin]]
name = "poll-server-client"
path = "src/poll-server-client/poll-async.rs"

[dependencies]
libc = "0.2.172"
