[package]
name = "rut-io-example"
version = "0.1.0"
edition = "2024"

[features]
linux = []
macos = ["nix/event"]

[[bin]]
name = "blocking-server"
path = "src/blocking-server/blocking_server.rs"

[[bin]]
name = "poll-server"
path = "src/poll_server/poll_server.rs"

[[bin]]
name = "epoll-server"
path = "src/epoll_server/epoll_server.rs"
required-features = ["linux"]

[[bin]]
name = "kqueue-server"
path = "src/kqueue_server/kqueue_server.rs"
required-features = ["macos"]

[[bin]]
name = "async-runtime"
path = "src/async-runtime/poll-async.rs"

[[bin]]
name = "io-uring-server"
path = "src/io_uring_server/io_uring_server.rs"
required-features = ["linux"]


[dependencies]
libc = "0.2.172"
nix = { version = "0.30.1"}
io-uring = "0.7.8"
